Hotel 005 authorization - жирненький вышел ;)
Gesheft-Rves/hotel pull request #5
Opened 2018-04-17 17:31 UTC by Gesheft-Rves

2018-04-26 16:15 UTC, zor07 requested changes

2018-04-26 16:15 UTC, zor07 commented on src/main/java/com/rves/Dto/BookingDto.java
>  public class BookingDto {
Посмотри 
private Timestamp date_buking;
 private Date date_of_departure;

Разные типы для одного и того же. Давай везде Timestamp юзать

2018-04-26 16:15 UTC, zor07 commented on src/main/java/com/rves/Dto/UserDto.java
> +public class UserDto {
Замени во всех классах солянку из геттеров-сеттеров на ломбоковские @Getter @Setter

2018-04-26 16:15 UTC, zor07 commented on src/main/java/com/rves/configuration/SecurityConfiguration.java
> +            .antMatchers("/resources/**", "/login/**").permitAll()
переименуй роли на SUPER, HOTEL_ADMIN, HOTEL_CLEANER

2018-04-26 16:15 UTC, zor07 commented on src/main/java/com/rves/controller/AuthorizationController.java
> +    private SecurityServiceImpl securityServiceImpl;
Лучше ставить не конкретную реализацию,а интерфейс. Это я про SecurityServiceImpl

2018-04-26 16:15 UTC, zor07 commented on src/main/java/com/rves/controller/MyAccessDeniedHandler.java
> +public class MyAccessDeniedHandler implements AccessDeniedHandler {
Красота ! Молодец что сам нагуглил и реализовал, хвалю!

2018-04-26 16:15 UTC, zor07 commented on src/main/java/com/rves/controller/MyAccessDeniedHandler.java
> +            logger.info("User '" + auth.getName() + "' attempted to access the protected URL: " + httpServletRequest.getRequestURI());
Разберись с тем куда пишутся логи и скажи мне

2018-04-26 16:15 UTC, zor07 commented on src/main/java/com/rves/controller/UserController.java
> +//    @RequestMapping("/users/delete/{id}")
Не должно быть кучи закоменченного кода

2018-04-26 16:15 UTC, zor07 commented on src/main/java/com/rves/pojo/User.java
> +    public User() {
Конструктор должен располагалаться не тут

2018-04-26 16:15 UTC, zor07 commented on src/main/resources/messages.properties
>  error.message.invalid_date_of_departure=\u0414\u0430\u0442\u0430 \u0432\u044b\u0435\u0437\u0434\u0430 \u043d\u0435 \u043c\u043e\u0436\u0435\u0442 \u0438\u0434\u0442\u0438 \u0440\u0430\u043d\u044c\u04
С этим надо что то делать

2018-04-26 16:15 UTC, zor07 commented on src/main/resources/templates/booking/list.html
> +                    //две строки ниже нужны для секьюрити, тебе пока не надо
Убрать комменты лишние

2018-04-26 16:15 UTC, zor07 commented on src/main/resources/templates/users/details.html
> +                <!--<label class="col-sm-2 control-label">Пароль</label>-->
Убери лишнее

2018-05-04 15:48 UTC, Gesheft-Rves commented on src/main/java/com/rves/Dto/BookingDto.java
>  public class BookingDto {
Много чего затрагивает изменение этих полей, явное и самое яркое поиск свободной комнаты и веб, ломается все, потратил время на изменение и подгонку и по итогу ничего не получилось, пока оставлю так.

2018-05-04 15:49 UTC, Gesheft-Rves commented on src/main/java/com/rves/controller/AuthorizationController.java
> +    private SecurityServiceImpl securityServiceImpl;
не понял

2018-05-07 08:40 UTC, zor07 approved these changes

2018-05-07 08:40 UTC, zor07 commented on src/main/java/com/rves/controller/AuthorizationController.java
> +    private SecurityServiceImpl securityServiceImpl;
private SecurityServiceImpl securityServiceImpl; - конкретная реализация интерфеса
private SecurityService securityService; - просто интерфейс. Спринг сам подставит реализацию

2018-05-07 08:40 UTC, zor07 commented on src/main/java/com/rves/controller/MyAccessDeniedHandler.java
> +            logger.info("User '" + auth.getName() + "' attempted to access the protected URL: " + httpServletRequest.getRequestURI());
Куда ?

2018-05-07 16:09 UTC, merged